import { PERMISSIONS, type Permission } from './permissions'

// ── Default Role Permission Bundles ───────────────────────────
// Schools can create custom roles — these are the defaults
// Parent and Student permissions are fixed (not customisable)

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
    // Management shell roles
    SUPER_ADMIN: Object.values(PERMISSIONS),

    ADMIN: [
        PERMISSIONS.FEES_VIEW, PERMISSIONS.FEES_COLLECT,
        PERMISSIONS.FEES_WAIVE, PERMISSIONS.FEES_REPORT,
        PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_REPORT,
        PERMISSIONS.STUDENTS_VIEW, PERMISSIONS.STUDENTS_CREATE,
        PERMISSIONS.STUDENTS_EDIT, PERMISSIONS.STUDENTS_DELETE,
        PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE,
        PERMISSIONS.GRADES_VIEW, PERMISSIONS.GRADES_REPORT,
        PERMISSIONS.TIMETABLE_VIEW, PERMISSIONS.TIMETABLE_MANAGE,
        PERMISSIONS.COURSES_VIEW, PERMISSIONS.COURSES_MANAGE,
        PERMISSIONS.VIBE_VIEW, PERMISSIONS.VIBE_POST, PERMISSIONS.VIBE_MODERATE,
        PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
        PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.ROLES_VIEW, PERMISSIONS.ROLES_MANAGE,
        PERMISSIONS.BUS_VIEW, PERMISSIONS.BUS_MANAGE,
        PERMISSIONS.AI_INSIGHTS, PERMISSIONS.AI_LESSON_PLAN,
        PERMISSIONS.MASQUERADE_READ_ONLY,
        PERMISSIONS.AUDIT_VIEW,
        PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_UPLOAD,
        PERMISSIONS.CALENDAR_VIEW, PERMISSIONS.CALENDAR_MANAGE,
        PERMISSIONS.TICKETS_VIEW,
        PERMISSIONS.COMMUNICATIONS_VIEW,
    ],

    TEACHER: [
        PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MARK,
        PERMISSIONS.ATTENDANCE_REPORT,
        PERMISSIONS.STUDENTS_VIEW,
        PERMISSIONS.GRADES_VIEW, PERMISSIONS.GRADES_ENTER,
        PERMISSIONS.TIMETABLE_VIEW,
        PERMISSIONS.COURSES_VIEW,
        PERMISSIONS.VIBE_VIEW, PERMISSIONS.VIBE_POST,
        PERMISSIONS.REPORTS_VIEW,
        PERMISSIONS.AI_INSIGHTS, PERMISSIONS.AI_LESSON_PLAN,
    ],

    INSTRUCTOR: [
        PERMISSIONS.COURSES_VIEW, PERMISSIONS.COURSES_CREATE,
        PERMISSIONS.COURSES_MANAGE,
        PERMISSIONS.STUDENTS_VIEW,
        PERMISSIONS.VIBE_VIEW, PERMISSIONS.VIBE_POST,
        PERMISSIONS.REPORTS_VIEW,
    ],

    // Consumer shell roles (fixed — not customisable by school)
    PARENT: [
        PERMISSIONS.FEES_VIEW,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.GRADES_VIEW,
        PERMISSIONS.TIMETABLE_VIEW,
        PERMISSIONS.VIBE_VIEW,
        PERMISSIONS.BUS_VIEW,
        PERMISSIONS.COURSES_VIEW,
    ],

    STUDENT: [
        PERMISSIONS.FEES_VIEW,
        PERMISSIONS.ATTENDANCE_VIEW,
        PERMISSIONS.GRADES_VIEW,
        PERMISSIONS.TIMETABLE_VIEW,
        PERMISSIONS.VIBE_VIEW, PERMISSIONS.VIBE_POST,
        PERMISSIONS.COURSES_VIEW, PERMISSIONS.COURSES_ENROLL,
    ],
}
